### ISSUE TITLE
Migration config v2 : A Cldr backend module must be configured

### ISSUE THREAD

**Issue by Cochonours** [kipcole9/cldr#102]
Could you be more clear about the migration? I used to have a working config for my pet project in config.ex:
```
config :ex_cldr,
  default_locale: "fr",
  gettext: TotoWeb.Gettext,
  json_library: Jason
```
I removed it to create a module, and as you never say where to put it (and it's a pet project to learn Elixir so I don't know enough to guess your intent) I put it in `lib/toto/Cldr.ex`. The compilation goes well, but when I try to go on a webpage I get the error "A Cldr backend module must be configured" (from calls to `plug Cldr.Plug.SetLocale`). **Wasn't the Toto.Cldr module the backend module I had to configure?** What else am I supposed to do?

**Comment by kipcole9** [comment]
@Cochonours apologies for the inconvenience.  It sounds like your `Toto.Cldr` backend module is fine.  This module hosts the public API for the `ex_cldr` and friends as you have discovered.

However the plug `Cldr.Plug.SetLocale` also needs to know which backend to use since `Plug` uses compile-time configuration.  You will see the configuration requirements if you `h Cldr.Plug.SetLocale` in `iex`.

I'm not sure how you're configuring the plug but it should now look something like this:
```
 plug Cldr.Plug.SetLocale,
    apps:    [cldr: Toto.Cldr],
    .....
```
I'll update the migration documentation to be more specific about the need to add configuration to the provided plugs.

Let me know if you have any other challenges finishing your migration?

**Comment by Cochonours** [comment]
Thanks!

After upgrading all the occurrences of the SetLocale plug, everything is working fine.

**Comment by kipcole9** [comment]
Glad its working for you now.  I have updated the readme with a simple migration section and republished the docs to hex.  Thanks for the issue report.
