### ISSUE TITLE
GenStage/Flow in mix.exs

### ISSUE THREAD

**Issue by LostKobrakai** [kipcole9/cldr#23]
Can we limit the usage of genstage/flow to only a certain mix env or maybe make it runtime: false? From what I can tell it's not going to be used in compiled production code.

**Comment by kipcole9** [comment]
I’m a bit conflicted on this too.  Flow is only used at compile time in Cldr.Config but it makes a big difference on my machines from a performance perspective.  Setting Flow to `runtime: false` was getting conflict errors from Mix since GenStage isn’t set that way.  I’ll do some more experimentation in my morning and see if I can reduce the requirement. I agree it would be preferable to avoid having them required at runtime.

**Comment by LostKobrakai** [comment]
Setting both as `runtime: false` seems to not cause any issue on a small test I did without actually using flow.

**Comment by kipcole9** [comment]
Agreed, I tried the same.  I need to test with a release to make sure that also works which I’ll do later today.

**Comment by kipcole9** [comment]
Refactored the code in `Cldr.Config.known_number_system_types/0` to use `Task.async_stream/3` rather than `Flow`.  Removed the dependency for `Flow` and set `GenStage` to be `optional: true, only: [:dev, :test]`

Push to hex as 0.13.1.

Thanks for the prompt, this feels much cleaner.

**Comment by LostKobrakai** [comment]
I think with GenStage only be used in `:dev` and `:test` it wouldn't even need to be optional.

**Comment by kipcole9** [comment]
I left it optional because GenStage is only used for the mix task to consolidate - and realistically thats something only i would do when a new CLDR release is made.

If i understand correctly, a client library using ex_cldr would install GenStage in `:dev` and `:test` if it wasn't optional.  Which I think we both agree shouldn't be a requirement for most people?

**Comment by LostKobrakai** [comment]
Ah sure, I must have misread something about that earlier today.
