### ISSUE TITLE
Not found locale for `pt-BR`

### ISSUE THREAD

**Issue by mbenatti** [kipcole9/cldr#42]
Using       {:ex_money, "~> 2.1.0-rc.1"}
Elixir 1.6

```Shell
== Compilation error in file lib/cldr.ex ==
** (Cldr.UnknownLocaleError) Some locale names are configured that are not known to CLDR. Compilation cannot continue until the configuration includes only locales names known in CLDR.

Configured locales names: ["en", "en-001", "en-GB", "es", "pt", "pt-BR", "root", "ru"]
Gettext locales names:    []
Unknown locales names:    ["pt-BR"]
```

**Comment by LostKobrakai** [comment]
As far as I can see there's no dataset for pt-BR in cldr: https://github.com/unicode-cldr/cldr-localenames-full/tree/master/main

**Comment by kipcole9** [comment]
The locale `pt-BR` exists in the master XML data for CLDR version 32 (the current version) but for some reason not in the json data for version 31 or 32.

Some googling suggests that Unicode considers Brazilian Portuguese as the canonical form and therefore the locale "pt" is Brazilian Portuguese.  I cannot verify that myself since I don't speak any kind of Portuguese.  Would you consider selecting installing "pt" and seeing if that looks to be the right content?

I will file an issue against CLDR and enquire on the `cldr-users` mailing list to see what the official position is.

I will revert here ASAP.

**Comment by kipcole9** [comment]
Sent to the `cldr-users@unicode.com` mailing list:
> I observe that the XML master data for CLDR versions 31 and 32 include the locale “pt-BR” but the json repo does not. May I ask if:
>
>(a) I should file an issue because the json repo should include pt-BR?
>(b) the locale “pt” is considered to be Brazilian Portuguese as some googling suggests?

**Comment by mbenatti** [comment]
@kipcole9 Using currency "BRL" I have the results expected...

**Comment by kipcole9** [comment]
Confirmed with the Unicode community that "pt" is Brazilian Portuguese.  This is consistent with the approach for "en" which is US english.

> Hi Kip,
>
>Your item (b) is correct... You may notice that pt_BR.xml is empty, which means it's the default content for pt.xml. Note pt_PT.xml has "Portuguese as spoken in Portugal" overrides only. Others could provide additional details and correct me if I'm wrong.
